In [2]:
import numpy as np
from sklearn.decomposition import FastICA

S=np.array([[1,1],[2,-1],[3,1],[4,-1]])
#Mix them
A=np.array([[1,2],[3,4]])
X = S@A.T
ica = FastICA(n_components=2,random_state=0)
U=ica.fit_transform(X)
print("Origina Sources :\n",S)
print("Recovered Sorurces (approx):\n",U)

Origina Sources :
 [[ 1  1]
 [ 2 -1]
 [ 3  1]
 [ 4 -1]]
Recovered Sorurces (approx):
 [[-1.  1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1. -1.]]


In [3]:
from sklearn.neural_network import MLPRegressor

X=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]],dtype=float)

autoencoders = MLPRegressor(hidden_layer_sizes=(2,),activation="relu",max_iter=5000,random_state=0)

autoencoders.fit(X,X)

X_reconstructed = autoencoders.predict(X)

W=autoencoders.coefs_[0]
b=autoencoders.intercepts_[0]
hidden_2d = np.maximum(0,X@W+b)

print("Hidden 4 features ",X)
print("\nHidden (2 Features) ",np.round(hidden_2d,2))
print("\nReconstruction :\n",np.round(X_reconstructed,2))


Hidden 4 features  [[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]

Hidden (2 Features)  [[4.35 1.56]
 [5.81 2.11]
 [7.27 2.66]
 [8.74 3.21]]

Reconstruction :
 [[2.05 2.76 3.4  3.99]
 [2.52 3.33 4.09 5.  ]
 [2.99 3.89 4.78 6.  ]
 [3.45 4.45 5.47 7.  ]]


In [4]:
#Implementation of active learning
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

#Create simple dataset
X,y=make_classification(n_samples=100,n_features=2,n_redundant=0,n_informative=2,random_state=0)

labeled=np.arange(10)
unlabeled = np.arange(10,100)

model=LogisticRegression(solver="liblinear")

for i in range(5):
    model.fit(X[labeled],y[labeled])
    probs = model.predict_proba(X[unlabeled])[:,1]

    query=np.argmin(np.abs(probs-0.5))

    labeled =np.append(labeled,unlabeled[query])
    unlabeled = np.delete(unlabeled,query)
    print("iteration ",i+1," | labeled size ",len(labeled))

iteration  1  | labeled size  11
iteration  2  | labeled size  12
iteration  3  | labeled size  13
iteration  4  | labeled size  14
iteration  5  | labeled size  15


In [7]:

## to classify data by computing wiighted

# Simple 1D input data
X=np.array([[1],[2],[3],[4]])
y=np.array([0,0,1,1])

centers = np.array([[1],[4]])
sigma = 1.0

def rbf(x,c):
    return np.exp(-np.linalg.norm(x-c)**2/(2*sigma**2))
H = np.array([[rbf(x,c) for c in centers] for x in X])

w=np.linalg.pinv(H) @ y

y_pred = H@w
y_pred_class = (y_pred>0.5).astype(int)

print("Predicted ",y_pred_class)

Predicted  [0 0 1 1]
